deployment:
  tasks:
    - export APP_PATH=/home/dppackde/repositories/derakhshan-front

    - /bin/echo "🚀 Pulling latest changes..."
    - /usr/local/bin/git --work-tree=$APP_PATH --git-dir=$APP_PATH/.git pull origin main

    - /bin/echo "📦 Installing dependencies..."
    - /usr/local/bin/npm install --prefix $APP_PATH

    - /bin/echo "🏗️ Building project..."
    - /usr/local/bin/npm run build --prefix $APP_PATH

    - /bin/echo "🔁 Restarting application..."
    - /usr/local/bin/pm2 restart front || /usr/local/bin/pm2 start $APP_PATH/server.js --name front
